# Generated by Django 4.2.13 on 2024-05-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='champion_index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EN', models.CharField(max_length=32)),
                ('KR', models.CharField(max_length=32)),
            ],
        ),
    ]
