upstream django {
    server unix:/tmp/gunicorn.sock fail_timeout=0;
}

server {
    listen 8080;
    server_name localhost;
    
    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;
    client_max_body_size 10M;

    location /static/ {
        alias /usr/src/app/static_root/; 
    }

    # 🚨🚨 location 블록 수정: try_files를 사용해 Nginx의 기본 페이지를 우회합니다. 🚨🚨
    location / {
        # 파일이 존재하면 서빙하고, 없으면 @proxy_to_django 블록으로 이동
        try_files $uri @proxy_to_django; 
    }

    # Gunicorn 프록시를 위한 전용 블록
    location @proxy_to_django {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
        
        proxy_pass http://django;
    }
}
