upstream django {
    server unix:/tmp/gunicorn.sock fail_timeout=0;
}

server {
    listen 8080;
    server_name localhost;
    
    root /usr/src/app/static; 

    # 🚨🚨 타임아웃 및 버퍼 설정을 서버 블록에 보강 🚨🚨
    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;
    client_max_body_size 10M; # 최대 업로드 파일 크기
    
    client_body_in_file_only clean;
    client_body_buffer_size 32k;

    location /static/ {
        alias /usr/src/app/static/; 
        expires 30d;
        access_log off;
    }

    location / {
        try_files $uri @proxy_to_django; 
    }

    location @proxy_to_django {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
        
        proxy_pass http://django;
    }
}
